# Generated by Django 5.2.8 on 2025-11-23 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('category', models.CharField(choices=[('devices', 'أجهزة'), ('courses', 'كورسات'), ('jobs', 'وظائف'), ('clinics', 'عيادات'), ('sessions', 'جلسات'), ('general', 'عام')], default='general', max_length=20, verbose_name='الفئة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('image', models.ImageField(blank=True, null=True, upload_to='feed/images/', verbose_name='صورة')),
                ('video', models.FileField(blank=True, null=True, upload_to='feed/videos/', verbose_name='فيديو')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور؟')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='عدد الإعجابات')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='عدد التعليقات')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.userprofile', verbose_name='المؤلف')),
            ],
            options={
                'verbose_name': 'منشور',
                'verbose_name_plural': 'المنشورات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='عدد الإعجابات')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.userprofile', verbose_name='المؤلف')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feed.comment', verbose_name='رد على')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed.post', verbose_name='المنشور')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المتابعة')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='accounts.userprofile', verbose_name='المتابع')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='accounts.userprofile', verbose_name='المتابَع')),
            ],
            options={
                'verbose_name': 'متابعة',
                'verbose_name_plural': 'المتابعات',
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإعجاب')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='feed.comment', verbose_name='التعليق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='accounts.userprofile', verbose_name='المستخدم')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='feed.post', verbose_name='المنشور')),
            ],
            options={
                'verbose_name': 'إعجاب',
                'verbose_name_plural': 'الإعجابات',
                'unique_together': {('user', 'comment'), ('user', 'post')},
            },
        ),
    ]
