# Generated by Django 5.2.8 on 2025-11-23 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الوظيفة')),
                ('description', models.TextField(verbose_name='الوصف والتفاصيل')),
                ('location', models.CharField(max_length=100, verbose_name='موقع العمل')),
                ('is_full_time', models.BooleanField(default=True, verbose_name='دوام كامل؟')),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='نطاق الراتب المتوقع')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='accounts.userprofile', verbose_name='الجهة المعلنة')),
            ],
            options={
                'verbose_name': 'وظيفة شاغرة',
                'verbose_name_plural': 'الوظائف',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(verbose_name='رسالة التقديم/السيرة الذاتية')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('reviewed', 'تمت المراجعة'), ('interview', 'دعوة لمقابلة'), ('rejected', 'تم الرفض'), ('hired', 'تم التوظيف')], default='pending', max_length=20, verbose_name='الحالة')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_applications', to='accounts.userprofile', verbose_name='المتقدم')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpost', verbose_name='الوظيفة المقدم لها')),
            ],
            options={
                'verbose_name': 'طلب وظيفة',
                'verbose_name_plural': 'طلبات الوظائف',
                'unique_together': {('job', 'applicant')},
            },
        ),
    ]
