# Generated by Django 5.2.8 on 2025-11-23 19:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('session_date', models.DateTimeField(verbose_name='تاريخ الجلسة')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='المدة (ساعة)')),
                ('location_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط العرض')),
                ('location_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط الطول')),
                ('location_address', models.TextField(verbose_name='عنوان الجلسة')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر بالساعة')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_patient', to='accounts.userprofile', verbose_name='المريض')),
                ('specialist', models.ForeignKey(limit_choices_to={'role': 'specialist'}, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_specialist', to='accounts.userprofile', verbose_name='الأخصائي')),
            ],
            options={
                'verbose_name': 'جلسة',
                'verbose_name_plural': 'الجلسات',
                'ordering': ['session_date'],
            },
        ),
        migrations.CreateModel(
            name='SessionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='التقييم')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reviews', to='accounts.userprofile', verbose_name='المقيّم')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='home_sessions.session', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'تقييم جلسة',
                'verbose_name_plural': 'تقييمات الجلسات',
            },
        ),
        migrations.CreateModel(
            name='SpecialistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('location_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط العرض')),
                ('location_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط الطول')),
                ('location_address', models.TextField(verbose_name='العنوان')),
                ('service_radius_km', models.PositiveIntegerField(default=10, verbose_name='نطاق الخدمة (كم)')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر بالساعة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح؟')),
                ('specialist', models.ForeignKey(limit_choices_to={'role': 'specialist'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.userprofile', verbose_name='الأخصائي')),
            ],
            options={
                'verbose_name': 'توفر أخصائي',
                'verbose_name_plural': 'توفر الأخصائيين',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='availability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_sessions.specialistavailability', verbose_name='التوفر'),
        ),
    ]
