# Generated by Django 5.2.8 on 2025-11-23 19:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=255, verbose_name='اسم العيادة')),
                ('slug', models.SlugField(unique=True, verbose_name='رابط العيادة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(default='مصر', max_length=100, verbose_name='الدولة')),
                ('phone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('subscription_tier', models.CharField(choices=[('basic', 'أساسي'), ('professional', 'احترافي'), ('enterprise', 'مؤسسي')], default='basic', max_length=20, verbose_name='نوع الاشتراك')),
                ('subscription_start', models.DateTimeField(blank=True, null=True, verbose_name='بداية الاشتراك')),
                ('subscription_end', models.DateTimeField(blank=True, null=True, verbose_name='نهاية الاشتراك')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('company', models.ForeignKey(limit_choices_to={'role': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='accounts.userprofile', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'عيادة',
                'verbose_name_plural': 'العيادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('appointment_date', models.DateTimeField(verbose_name='تاريخ الموعد')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='المدة (دقيقة)')),
                ('status', models.CharField(choices=[('scheduled', 'مجدول'), ('confirmed', 'مؤكد'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('no_show', 'لم يحضر')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.userprofile', verbose_name='الطبيب')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.clinic', verbose_name='العيادة')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
                'ordering': ['appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('diagnosis', models.TextField(verbose_name='التشخيص')),
                ('treatment_plan', models.TextField(verbose_name='خطة العلاج')),
                ('prescription', models.TextField(blank=True, verbose_name='الوصفة الطبية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_notes', to='clinics.appointment', verbose_name='الموعد')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile', verbose_name='الطبيب')),
            ],
            options={
                'verbose_name': 'ملاحظة طبية',
                'verbose_name_plural': 'الملاحظات الطبية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='الاسم الأخير')),
                ('phone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('medical_history', models.TextField(blank=True, verbose_name='التاريخ الطبي')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clinics.clinic', verbose_name='العيادة')),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الضريبة')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع'), ('overdue', 'متأخر'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='طريقة الدفع')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinics.appointment', verbose_name='الموعد')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clinics.clinic', verbose_name='العيادة')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clinics.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.patient', verbose_name='المريض'),
        ),
    ]
