# Generated by Django 5.2.8 on 2025-11-24 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=120, verbose_name='Dataset Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Source / Reference')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Effective Date')),
            ],
            options={
                'verbose_name': 'Dataset Snapshot',
                'verbose_name_plural': 'Dataset Snapshots',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CountryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('country', models.CharField(max_length=120, verbose_name='Country')),
                ('continent', models.CharField(max_length=60, verbose_name='Continent')),
                ('population', models.BigIntegerField(default=0, verbose_name='Population')),
                ('therapists', models.IntegerField(default=0, verbose_name='Registered Therapists')),
                ('schools', models.IntegerField(default=0, verbose_name='Therapy Schools / Colleges')),
                ('centers', models.IntegerField(default=0, verbose_name='Rehab Centers')),
                ('avg_salary_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Avg Salary (USD)')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_stats', to='global_stats.datasetsnapshot')),
            ],
            options={
                'verbose_name': 'Country Stat',
                'verbose_name_plural': 'Country Stats',
                'ordering': ['dataset', 'country'],
            },
        ),
    ]
