# Generated by Django 5.2.8 on 2025-11-23 19:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحملة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الميزانية')),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المصروف')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('paused', 'متوقف'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.userprofile', verbose_name='المعلن')),
            ],
            options={
                'verbose_name': 'حملة إعلانية',
                'verbose_name_plural': 'الحملات الإعلانية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='صورة')),
                ('link_url', models.URLField(blank=True, verbose_name='رابط الإعلان')),
                ('ad_type', models.CharField(choices=[('banner', 'بانر'), ('sidebar', 'شريط جانبي'), ('feed', 'في Feed'), ('popup', 'نافذة منبثقة')], default='banner', max_length=20, verbose_name='نوع الإعلان')),
                ('target_audience', models.JSONField(blank=True, default=dict, verbose_name='الجمهور المستهدف')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='عدد النقرات')),
                ('ctr', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة النقر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.campaign', verbose_name='الحملة')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='المشاهدات')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='النقرات')),
                ('conversions', models.PositiveIntegerField(default=0, verbose_name='التحويلات')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='ads.ad', verbose_name='الإعلان')),
            ],
            options={
                'verbose_name': 'تحليل إعلان',
                'verbose_name_plural': 'تحليلات الإعلانات',
                'ordering': ['-date'],
                'unique_together': {('ad', 'date')},
            },
        ),
    ]
