# Generated by Django 5.2.8 on 2025-11-23 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحملة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], max_length=20, verbose_name='القناة')),
                ('message_template', models.TextField(verbose_name='نموذج الرسالة')),
                ('target_audience', models.JSONField(blank=True, default=dict, verbose_name='الجمهور المستهدف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('scheduled', 'مجدول'), ('running', 'قيد التشغيل'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='عدد المرسل')),
                ('delivered_count', models.PositiveIntegerField(default=0, verbose_name='عدد الموصول')),
            ],
            options={
                'verbose_name': 'حملة CRM',
                'verbose_name_plural': 'حملات CRM',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='الاسم الأخير')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='الهاتف')),
                ('source', models.CharField(choices=[('website', 'الموقع'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('referral', 'إحالة'), ('other', 'أخرى')], default='website', max_length=50, verbose_name='المصدر')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم الاتصال'), ('qualified', 'مؤهل'), ('converted', 'محول'), ('lost', 'مفقود')], default='new', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to='accounts.userprofile', verbose_name='مخصص لـ')),
            ],
            options={
                'verbose_name': 'جهة اتصال',
                'verbose_name_plural': 'جهات الاتصال',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS'), ('facebook', 'Facebook')], max_length=20, verbose_name='القناة')),
                ('direction', models.CharField(choices=[('inbound', 'وارد'), ('outbound', 'صادر')], max_length=10, verbose_name='الاتجاه')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('status', models.CharField(choices=[('sent', 'مرسل'), ('delivered', 'تم التسليم'), ('read', 'مقروء'), ('failed', 'فشل')], default='sent', max_length=20, verbose_name='الحالة')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.contact', verbose_name='جهة الاتصال')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['-created_at'],
            },
        ),
    ]
