# Generated by Django 5.2.8 on 2025-11-23 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم التمرين')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('instructions', models.TextField(verbose_name='التعليمات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/', verbose_name='صورة')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='رابط الفيديو')),
                ('category', models.CharField(choices=[('strength', 'تقوية'), ('flexibility', 'مرونة'), ('balance', 'توازن'), ('cardio', 'قلبي وعائي'), ('rehabilitation', 'إعادة تأهيل')], max_length=50, verbose_name='الفئة')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='beginner', max_length=20, verbose_name='مستوى الصعوبة')),
                ('duration_minutes', models.PositiveIntegerField(default=10, verbose_name='المدة (دقيقة)')),
                ('repetitions', models.PositiveIntegerField(default=10, verbose_name='عدد التكرارات')),
            ],
            options={
                'verbose_name': 'تمرين',
                'verbose_name_plural': 'التمارين',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('query', models.TextField(verbose_name='استعلام البحث')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='عدد النتائج')),
                ('response_time_ms', models.PositiveIntegerField(default=0, verbose_name='وقت الاستجابة (ميللي ثانية)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to='accounts.userprofile', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل بحث',
                'verbose_name_plural': 'سجلات البحث',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('condition', models.CharField(max_length=255, verbose_name='الحالة')),
                ('diagnosis', models.TextField(verbose_name='التشخيص')),
                ('treatment_plan', models.TextField(verbose_name='خطة العلاج')),
                ('exercises', models.JSONField(blank=True, default=list, verbose_name='التمارين')),
                ('duration_weeks', models.PositiveIntegerField(default=4, verbose_name='المدة (أسابيع)')),
                ('is_ai_generated', models.BooleanField(default=True, verbose_name='مولّد بالذكاء الاصطناعي؟')),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treatment_plans', to='accounts.userprofile', verbose_name='الطبيب')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='accounts.userprofile', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'خطة علاج',
                'verbose_name_plural': 'خطط العلاج',
                'ordering': ['-created_at'],
            },
        ),
    ]
