# Generated by Django 5.2.8 on 2025-11-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquivalenceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name_ar', models.CharField(help_text='The full name of the country in Arabic (e.g., المملكة العربية السعودية).', max_length=100, unique=True, verbose_name='Country Name (Arabic)')),
                ('country_code', models.CharField(help_text='The two-letter ISO country code (e.g., SA for Saudi Arabia, US for USA).', max_length=2, unique=True, verbose_name='Country Code (ISO 2)')),
                ('official_requirements', models.TextField(help_text='Detailed list of formal papers and registrations.', verbose_name='Official Requirements')),
                ('theoretical_practical_hours', models.TextField(help_text='Details about required academic and practical hours.', verbose_name='Theoretical and Practical Hours')),
                ('mandatory_exams', models.TextField(help_text='Information about licensing exams (e.g., Prometric, MOH).', verbose_name='Mandatory Exams')),
                ('general_notes', models.TextField(blank=True, null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Equivalence Requirement',
                'verbose_name_plural': 'Equivalence Requirements',
                'ordering': ['country_name_ar'],
                'indexes': [models.Index(fields=['country_code'], name='content_equ_country_b9d597_idx'), models.Index(fields=['country_name_ar'], name='content_equ_country_253cdc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExploreDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Country Name')),
                ('data_type', models.CharField(choices=[('THERAPISTS', 'Registered Therapists'), ('POPULATION', 'Relevant Population Size'), ('SCHOOLS', 'Schools/Colleges'), ('REHAB_CENTERS', 'Rehab Centers')], max_length=50, verbose_name='Data Type')),
                ('value', models.IntegerField(verbose_name='Data Value')),
                ('year', models.IntegerField(default=2024, verbose_name='Year of Data')),
            ],
            options={
                'verbose_name': 'Explore Data Point',
                'verbose_name_plural': 'Explore Data Points',
                'ordering': ['-year', 'country', 'data_type'],
                'indexes': [models.Index(fields=['data_type'], name='content_exp_data_ty_a268b5_idx'), models.Index(fields=['country'], name='content_exp_country_9d543a_idx')],
                'unique_together': {('country', 'data_type', 'year')},
            },
        ),
    ]
