# Generated by Django 5.2.8 on 2025-11-24 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Country Code')),
                ('name_en', models.CharField(max_length=120, verbose_name='English Name')),
                ('name_local', models.CharField(blank=True, max_length=120, verbose_name='Local / Arabic Name')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Region')),
                ('continent', models.CharField(choices=[('africa', 'Africa'), ('asia', 'Asia'), ('europe', 'Europe'), ('americas', 'Americas'), ('oceania', 'Oceania'), ('global', 'Global')], default='asia', max_length=60, verbose_name='Continent')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='EquivalencyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('study_hours', models.CharField(blank=True, max_length=255, verbose_name='Study / Bridging Hours')),
                ('accredited_hours', models.CharField(blank=True, max_length=255, verbose_name='Accredited Hours')),
                ('language_requirement', models.CharField(blank=True, max_length=255, verbose_name='Language Requirement')),
                ('exam_requirement', models.CharField(blank=True, max_length=255, verbose_name='Exam / Assessment')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='equivalency.country')),
            ],
            options={
                'verbose_name': 'Equivalency Requirement',
                'verbose_name_plural': 'Equivalency Requirements',
                'ordering': ['country__name_en'],
            },
        ),
        migrations.CreateModel(
            name='RequirementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('description', models.TextField(blank=True, verbose_name='Description / Details')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Is Mandatory?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='equivalency.equivalencyrequirement')),
            ],
            options={
                'verbose_name': 'Requirement Document',
                'verbose_name_plural': 'Requirement Documents',
                'ordering': ['order', 'id'],
            },
        ),
    ]
