# Generated by Django 5.2.8 on 2025-11-24 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('provider', models.CharField(choices=[('paymob', 'Paymob'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], default='paymob', max_length=20)),
                ('display_name', models.CharField(max_length=120, verbose_name='Display Name')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key / Token')),
                ('hmac_secret', models.CharField(blank=True, max_length=255, verbose_name='HMAC Secret')),
                ('integration_id', models.CharField(blank=True, max_length=120, verbose_name='Integration ID')),
                ('iframe_id', models.CharField(blank=True, max_length=120, verbose_name='Iframe ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Extra Metadata')),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'ordering': ['provider', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('provider', models.CharField(choices=[('paymob', 'Paymob'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EGP', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('order_reference', models.CharField(blank=True, max_length=120)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('gateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.paymentgatewayconfig')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
