# Generated by Django 5.2.8 on 2025-11-23 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('patient', 'مريض'), ('doctor', 'طبيب'), ('specialist', 'أخصائي علاج طبيعي'), ('vendor', 'مورد أجهزة'), ('company', 'شركة/مركز طبي'), ('trainer', 'مدرب/محاضر'), ('admin', 'مسؤول النظام')], default='patient', max_length=20, verbose_name='الدور')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة تعريفية')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق من الوثائق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم الأساسي')),
            ],
            options={
                'verbose_name': 'ملف تعريف المستخدم',
                'verbose_name_plural': 'ملفات تعريف المستخدمين',
                'ordering': ['-created_at'],
            },
        ),
    ]
